package com.example.a1_composedocumentationuiarchitecture.Architecture_7

import androidx.compose.foundation.layout.Column
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.getValue
import androidx.compose.runtime.setValue
import androidx.compose.runtime.saveable.rememberSaveable

/*
In Jetpack Compose, UI is generated by functions marked with the @Composable annotation.
These functions describe what the UI should look like for a given state.
When that state changes, Compose intelligently re-runs the function
(a process called recomposition) to update only the necessary
parts of the UI.
*/

@Composable
fun NameEntryScreen(){
    Column{
        var name by rememberSaveable{mutableStateOf("")}
        OutlinedTextField(
            value = name,
            onValueChange = {name=it},
            label={Text("Enter the name")}
        )
    }
}